# Generated by Django 4.0 on 2022-04-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='main.blogcategory'),
        ),
    ]
